### ISSUE TITLE
support for websockets on win8+

### ISSUE THREAD

**Issue by tjanczuk** [tjanczuk/httpsys#14]

**Comment by matthiasg** [comment]
interesting issue. i just read your block and did not try it yet. i would not have expected websockets to be unsupported on win8+ .. why is that ?

**Comment by tjanczuk** [comment]
I have not written the code in httpsys module yet to expose this functionality to JavaScript. Once I do WebSockets will work only on Windows 8+, since HTTP.SYS in previous versions does not support HTTP Upgrade mechanism required to implement WebSockets.

**Comment by ghost** [comment]
Hi Tomasz,
Do you plan to implement a full WebSocket stack embedded inside the httpsys module or support the WebSocket-Node module (if possible) ?

**Comment by tjanczuk** [comment]
Strictly speaking the httpsys module will merely support the HTTP Upgrade mechanism that HTTP.SYS on WIndows 8 and Windows Server 2012 offers. It will be exposed to the node.js application using Server.on('connection') event, the same way HTTP upgrade is exposed in the built-in HTTP stack. From there, you should be able to use any existing node.js module (like socket.io or faye-websocket) that implements the WebSocket protocol on top of the HTTP Upgrade mechanism.

**Comment by tjanczuk** [comment]
Fixed as of 3b933b7186c1d2222c85bff10b48eb6640cb794d
