### ISSUE TITLE
port sharing

### ISSUE THREAD

**Issue by maciejjankowski** [tjanczuk/httpsys#20]
does it mean I can share socket.io and http on the same port?
I have been fighting over this last night and I finally settled on discarding express and handling requests 'by hand'. ugh!
So is it possible to use httpsys with express?

**Comment by tjanczuk** [comment]
In theory yes, with two caveats:
1. httpsys is still just an experiement. In particular, I am not sure whether the level of API compatibility with the built-in http module will allow you to run socket.io on top of it. 
2. httpsys does not support websockets yet.

**Comment by maciejjankowski** [comment]
that's a bummer.
first I was trying to run my app on two ports but it kept 500ing me and I had no idea what is wrong - probably something with configuration - I have hardly any idea on csdef and how to configure worker role to use two separate ports - one for http traffic, and the other for socket.io. Any comments how I could approach that?
What I want is an application that ideally would run on the same port and publish the contents of POST updates to connected socket.io or two separate ports - which ever is easier to do.

**Comment by tjanczuk** [comment]
I would start with the azure CLI you can get by running `npm install azure-cli -g` (see http://www.windowsazure.com/en-us/develop/nodejs/ for more information). The tool can then help you scaffold and publish a node.js app that listens on port 80 to a Windows Azure worker role without getting csdef in your eyes on the way. Once you have a node.js web server on port 80 running in a worker role, you can add socket.io code to it just like all socket.io samples out there show you.

**Comment by maciejjankowski** [comment]
cli (PS) keeps failing gracefully while uploading cspkg and I have to
ctrl+c it. Then manually upload cspkg.
I was not able to have express and socket.io run on azure. They wouldn't
live on one port for some reason that is beyond my comprehension.

**Comment by tjanczuk** [comment]
For the "cli keeps failing gracefully while uploading cspkg" problem, can you file it at https://github.com/WindowsAzure/azure-sdk-tools-xplat/issues/new and I will make sure someone will look into it? Please provide more details: node.js version, cli version, how it fails exactly. Note the process of deploying a node app that way typically takes several minutes. 

Once you upload cspkg manually, what is the symptom you are seeing? Are you able to get a simple 'hello, world' working that way?

**Comment by maciejjankowski** [comment]
I rewrote the app and it magically worked this time! I guess it counts as
sweat equity :-)
That's what worked this time. Yay!

var express = require('express')
, http = require('http')
, path = require('path')
, app = express()
, formidable = require('formidable'),

app.configure(function(){
  app.set('port', 80);
  app.use(express.favicon());
  app.use(express.logger('dev'));
  app.use(express.bodyParser());
  app.use(express.methodOverride());
  app.use(app.router);
  app.use(express.static(path.join(__dirname, 'public')));
  app.use(function(req,res){
res.writeHead(200, {'content-type': 'text/plain'});
if (req.method.toLowerCase() == 'post') {
var form = new formidable.IncomingForm();
form.parse(req, function(err, fields, files) {
io.sockets.emit("form", fields);
});
}
res.write("nikogo nie ma w domu");
res.end();
}) //app.use
}); //app.configure

app.post('/*', function(req, res){
io.sockets.emit("form", req.body);
res.json(req.body);
});
server = http.createServer(app);
server.listen(80); //process.env.port ||
var io = require('socket.io').listen(server);

**Comment by tjanczuk** [comment]
Glad it worked.
