### ISSUE TITLE
System Error 87 when attempting to listen

### ISSUE THREAD

**Issue by jmatthewsr-ms** [tjanczuk/httpsys#22]
Hey, 

I modified httpsys.cc slightly to print out the file and line for the following error.  The function that is failing appears to be:

CheckError(HttpAddUrlToUrlGroup(
            uv_httpsys_server->groupId,
            url,
            0,
            NULL));

I'm running node in a console run as Administrator. Both 32 and 64-bit versions of node.exe version 0.8.12. Here is the code: https://github.com/jmatthewsr-ms/socketio-multicore-httpsys

C:\skype\git\socketio-multicore-httpsys\node_modules\httpsys\lib\httpsys.js:402
        throw new Error('Error initializing the HTTP.SYS server. System error
              ^
Error: Error initializing the HTTP.SYS server. System error ..\src\httpsys.cc.730 Error Code: 87.
    at HttpServer.Server.listen (C:\skype\git\socketio-multicore-httpsys\node_modules\httpsys\lib\httpsys.js:402:15)
    at Object.<anonymous> (C:\skype\git\socketio-multicore-httpsys\server.js:15:5)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)

**Comment by tjanczuk** [comment]
Hi Justin,

the HttpAddUrlToUrlGroup API is rather unforgiving in what it accepts as a URL. Try adding a trailing slash to the URL before calling `listen` in https://github.com/jmatthewsr-ms/socketio-multicore-httpsys/blob/master/server.js#L13. That is, change:

```
urlListen = 'http://*:'+port;
```

to 

```
urlListen = 'http://*:'+port+'/';
```

Also note that the entire URL space under port 80 is by default ACLed for exclusive use by IIS, so first try a different port.

**Comment by tjanczuk** [comment]
You can check if port 80 is reserved with `netsh http show urlacl`.

**Comment by jmatthewsr-ms** [comment]
Adding the '/' worked thanks!
